#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamyWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SamyDatabase")]
	public partial class SamyDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SamyDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SamyDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SamyDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SamyDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SamyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SamyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bounsprod> Bounsprods
		{
			get
			{
				return this.GetTable<Bounsprod>();
			}
		}
		
		public System.Data.Linq.Table<curn> curns
		{
			get
			{
				return this.GetTable<curn>();
			}
		}
		
		public System.Data.Linq.Table<infac> infacs
		{
			get
			{
				return this.GetTable<infac>();
			}
		}
		
		public System.Data.Linq.Table<EmployeesFile> EmployeesFiles
		{
			get
			{
				return this.GetTable<EmployeesFile>();
			}
		}
		
		public System.Data.Linq.Table<instyp> instyps
		{
			get
			{
				return this.GetTable<instyp>();
			}
		}
		
		public System.Data.Linq.Table<prodin> prodins
		{
			get
			{
				return this.GetTable<prodin>();
			}
		}
		
		public System.Data.Linq.Table<T_boun> T_bouns
		{
			get
			{
				return this.GetTable<T_boun>();
			}
		}
		
		public System.Data.Linq.Table<T_dentyp> T_dentyps
		{
			get
			{
				return this.GetTable<T_dentyp>();
			}
		}
		
		public System.Data.Linq.Table<T_doc> T_docs
		{
			get
			{
				return this.GetTable<T_doc>();
			}
		}
		
		public System.Data.Linq.Table<T_docjop> T_docjops
		{
			get
			{
				return this.GetTable<T_docjop>();
			}
		}
		
		public System.Data.Linq.Table<T_docnam> T_docnams
		{
			get
			{
				return this.GetTable<T_docnam>();
			}
		}
		
		public System.Data.Linq.Table<T_instypnam> T_instypnams
		{
			get
			{
				return this.GetTable<T_instypnam>();
			}
		}
		
		public System.Data.Linq.Table<T_kst9> T_kst9s
		{
			get
			{
				return this.GetTable<T_kst9>();
			}
		}
		
		public System.Data.Linq.Table<T_passcod> T_passcods
		{
			get
			{
				return this.GetTable<T_passcod>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bounsprod")]
	public partial class Bounsprod
	{
		
		private int _cur;
		
		private int _ins;
		
		private int _yer;
		
		private System.Nullable<double> _bon;
		
		private System.Nullable<System.DateTime> _fdat;
		
		private System.Nullable<System.DateTime> _tdat;
		
		public Bounsprod()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cur", DbType="Int NOT NULL")]
		public int cur
		{
			get
			{
				return this._cur;
			}
			set
			{
				if ((this._cur != value))
				{
					this._cur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ins", DbType="Int NOT NULL")]
		public int ins
		{
			get
			{
				return this._ins;
			}
			set
			{
				if ((this._ins != value))
				{
					this._ins = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yer", DbType="Int NOT NULL")]
		public int yer
		{
			get
			{
				return this._yer;
			}
			set
			{
				if ((this._yer != value))
				{
					this._yer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bon", DbType="Float")]
		public System.Nullable<double> bon
		{
			get
			{
				return this._bon;
			}
			set
			{
				if ((this._bon != value))
				{
					this._bon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fdat", DbType="DateTime")]
		public System.Nullable<System.DateTime> fdat
		{
			get
			{
				return this._fdat;
			}
			set
			{
				if ((this._fdat != value))
				{
					this._fdat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tdat", DbType="DateTime")]
		public System.Nullable<System.DateTime> tdat
		{
			get
			{
				return this._tdat;
			}
			set
			{
				if ((this._tdat != value))
				{
					this._tdat = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.curn")]
	public partial class curn
	{
		
		private short _cod;
		
		private string _nam;
		
		private string _engnam;
		
		public curn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="SmallInt NOT NULL")]
		public short cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Char(20)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engnam", DbType="Char(20)")]
		public string engnam
		{
			get
			{
				return this._engnam;
			}
			set
			{
				if ((this._engnam != value))
				{
					this._engnam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.infac")]
	public partial class infac
	{
		
		private int _no;
		
		private int _idf;
		
		private int _idt;
		
		private int _sen;
		
		private System.Nullable<double> _qx;
		
		private System.Nullable<double> _lx;
		
		private System.Nullable<double> _dd;
		
		private System.Nullable<double> _vx;
		
		private System.Nullable<double> _dx;
		
		private System.Nullable<double> _nx;
		
		private System.Nullable<double> _sx;
		
		private System.Nullable<double> _cx;
		
		private System.Nullable<double> _mx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _rat;
		
		public infac()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="Int NOT NULL")]
		public int no
		{
			get
			{
				return this._no;
			}
			set
			{
				if ((this._no != value))
				{
					this._no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idf", DbType="Int NOT NULL")]
		public int idf
		{
			get
			{
				return this._idf;
			}
			set
			{
				if ((this._idf != value))
				{
					this._idf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idt", DbType="Int NOT NULL")]
		public int idt
		{
			get
			{
				return this._idt;
			}
			set
			{
				if ((this._idt != value))
				{
					this._idt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sen", DbType="Int NOT NULL")]
		public int sen
		{
			get
			{
				return this._sen;
			}
			set
			{
				if ((this._sen != value))
				{
					this._sen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qx", DbType="Float")]
		public System.Nullable<double> qx
		{
			get
			{
				return this._qx;
			}
			set
			{
				if ((this._qx != value))
				{
					this._qx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lx", DbType="Float")]
		public System.Nullable<double> lx
		{
			get
			{
				return this._lx;
			}
			set
			{
				if ((this._lx != value))
				{
					this._lx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dd", DbType="Float")]
		public System.Nullable<double> dd
		{
			get
			{
				return this._dd;
			}
			set
			{
				if ((this._dd != value))
				{
					this._dd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vx", DbType="Float")]
		public System.Nullable<double> vx
		{
			get
			{
				return this._vx;
			}
			set
			{
				if ((this._vx != value))
				{
					this._vx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dx", DbType="Float")]
		public System.Nullable<double> dx
		{
			get
			{
				return this._dx;
			}
			set
			{
				if ((this._dx != value))
				{
					this._dx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nx", DbType="Float")]
		public System.Nullable<double> nx
		{
			get
			{
				return this._nx;
			}
			set
			{
				if ((this._nx != value))
				{
					this._nx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sx", DbType="Float")]
		public System.Nullable<double> sx
		{
			get
			{
				return this._sx;
			}
			set
			{
				if ((this._sx != value))
				{
					this._sx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cx", DbType="Float")]
		public System.Nullable<double> cx
		{
			get
			{
				return this._cx;
			}
			set
			{
				if ((this._cx != value))
				{
					this._cx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mx", DbType="Float")]
		public System.Nullable<double> mx
		{
			get
			{
				return this._mx;
			}
			set
			{
				if ((this._mx != value))
				{
					this._mx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rat", DbType="Float")]
		public System.Nullable<double> rat
		{
			get
			{
				return this._rat;
			}
			set
			{
				if ((this._rat != value))
				{
					this._rat = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeesFiles")]
	public partial class EmployeesFile
	{
		
		private int _ID;
		
		private string _FileName;
		
		private System.Data.Linq.Binary _File;
		
		private System.Nullable<System.DateTime> _PostedFileDate;
		
		private string _LoggedUserName;
		
		private System.Nullable<int> _LoggedUserPassword;
		
		public EmployeesFile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[File]", Storage="_File", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary File
		{
			get
			{
				return this._File;
			}
			set
			{
				if ((this._File != value))
				{
					this._File = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostedFileDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PostedFileDate
		{
			get
			{
				return this._PostedFileDate;
			}
			set
			{
				if ((this._PostedFileDate != value))
				{
					this._PostedFileDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoggedUserName", DbType="VarChar(50)")]
		public string LoggedUserName
		{
			get
			{
				return this._LoggedUserName;
			}
			set
			{
				if ((this._LoggedUserName != value))
				{
					this._LoggedUserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoggedUserPassword", DbType="Int")]
		public System.Nullable<int> LoggedUserPassword
		{
			get
			{
				return this._LoggedUserPassword;
			}
			set
			{
				if ((this._LoggedUserPassword != value))
				{
					this._LoggedUserPassword = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.instyp")]
	public partial class instyp
	{
		
		private int _cod;
		
		private string _nam;
		
		public instyp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Char(30)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prodins")]
	public partial class prodin
	{
		
		private int _cod;
		
		private int _ser;
		
		private System.Nullable<System.DateTime> _brtd;
		
		private System.Nullable<System.DateTime> _brth2;
		
		private System.Nullable<int> _moda;
		
		private System.Nullable<int> _mab;
		
		private System.Nullable<System.DateTime> _strd;
		
		private System.Nullable<double> _kst;
		
		private System.Nullable<double> _prm;
		
		private System.Nullable<double> _ksty;
		
		private System.Nullable<int> _sen;
		
		private System.Nullable<int> _dentyp;
		
		private System.Nullable<double> _denval;
		
		private System.Nullable<double> _kst1;
		
		private System.Nullable<double> _nsb1;
		
		private System.Nullable<double> _esh1;
		
		private System.Nullable<double> _kst2;
		
		private System.Nullable<double> _nsb2;
		
		private System.Nullable<double> _esh2;
		
		private System.Nullable<double> _kst3;
		
		private System.Nullable<double> _nsb3;
		
		private System.Nullable<double> _esh3;
		
		private System.Nullable<double> _kst4;
		
		private System.Nullable<double> _nsb4;
		
		private System.Nullable<double> _esh4;
		
		private System.Nullable<double> _om11;
		
		private System.Nullable<double> _om21;
		
		private System.Nullable<double> _om31;
		
		private System.Nullable<double> _om41;
		
		private System.Nullable<double> _om51;
		
		private System.Nullable<double> _om12;
		
		private System.Nullable<double> _om22;
		
		private System.Nullable<double> _om32;
		
		private System.Nullable<double> _om42;
		
		private System.Nullable<double> _om52;
		
		private System.Nullable<double> _om13;
		
		private System.Nullable<double> _om23;
		
		private System.Nullable<double> _om33;
		
		private System.Nullable<double> _om43;
		
		private System.Nullable<double> _om53;
		
		private System.Nullable<double> _om14;
		
		private System.Nullable<double> _om24;
		
		private System.Nullable<double> _om34;
		
		private System.Nullable<double> _om44;
		
		private System.Nullable<double> _om54;
		
		private System.Nullable<int> _ded;
		
		private System.Nullable<System.DateTime> _sts;
		
		private string _nam;
		
		private string _nam2;
		
		private string _adr;
		
		private string _life;
		
		private string _deth;
		
		private string _phon;
		
		private string _phon2;
		
		private string _amil;
		
		private string _fax;
		
		private System.Nullable<decimal> _rkm;
		
		private System.Nullable<System.DateTime> _tday;
		
		private string _nam3;
		
		private string _pos1;
		
		private string _pos2;
		
		private string _pos3;
		
		private string _adr1;
		
		private string _adr2;
		
		private string _adr3;
		
		private System.Nullable<decimal> _numall1;
		
		private System.Nullable<decimal> _numall2;
		
		private System.Nullable<decimal> _numall3;
		
		private System.Nullable<int> _cur;
		
		private System.Nullable<int> _he1;
		
		private System.Nullable<int> _he2;
		
		private System.Nullable<int> _doc;
		
		private System.Nullable<double> _rpos1;
		
		private System.Nullable<double> _rpos2;
		
		private System.Nullable<double> _rhel1;
		
		private System.Nullable<double> _rhel2;
		
		private System.Nullable<double> _racc1;
		
		private System.Nullable<double> _racc2;
		
		private System.Nullable<double> _rdep1;
		
		private System.Nullable<double> _rdep2;
		
		private System.Nullable<double> _rpen1;
		
		private System.Nullable<double> _rpen2;
		
		private System.Nullable<int> _pascod;
		
		private System.Nullable<int> _omok;
		
		private System.Nullable<int> _modasdad;
		
		private System.Nullable<double> _pen1;
		
		private System.Nullable<double> _pen2;
		
		private System.Nullable<double> _pen3;
		
		private System.Nullable<double> _pen4;
		
		private System.Nullable<double> _penall;
		
		public prodin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser", DbType="Int NOT NULL")]
		public int ser
		{
			get
			{
				return this._ser;
			}
			set
			{
				if ((this._ser != value))
				{
					this._ser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brtd", DbType="DateTime")]
		public System.Nullable<System.DateTime> brtd
		{
			get
			{
				return this._brtd;
			}
			set
			{
				if ((this._brtd != value))
				{
					this._brtd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brth2", DbType="DateTime")]
		public System.Nullable<System.DateTime> brth2
		{
			get
			{
				return this._brth2;
			}
			set
			{
				if ((this._brth2 != value))
				{
					this._brth2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moda", DbType="Int")]
		public System.Nullable<int> moda
		{
			get
			{
				return this._moda;
			}
			set
			{
				if ((this._moda != value))
				{
					this._moda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mab", DbType="Int")]
		public System.Nullable<int> mab
		{
			get
			{
				return this._mab;
			}
			set
			{
				if ((this._mab != value))
				{
					this._mab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strd", DbType="DateTime")]
		public System.Nullable<System.DateTime> strd
		{
			get
			{
				return this._strd;
			}
			set
			{
				if ((this._strd != value))
				{
					this._strd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kst", DbType="Float")]
		public System.Nullable<double> kst
		{
			get
			{
				return this._kst;
			}
			set
			{
				if ((this._kst != value))
				{
					this._kst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prm", DbType="Float")]
		public System.Nullable<double> prm
		{
			get
			{
				return this._prm;
			}
			set
			{
				if ((this._prm != value))
				{
					this._prm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ksty", DbType="Float")]
		public System.Nullable<double> ksty
		{
			get
			{
				return this._ksty;
			}
			set
			{
				if ((this._ksty != value))
				{
					this._ksty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sen", DbType="Int")]
		public System.Nullable<int> sen
		{
			get
			{
				return this._sen;
			}
			set
			{
				if ((this._sen != value))
				{
					this._sen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dentyp", DbType="Int")]
		public System.Nullable<int> dentyp
		{
			get
			{
				return this._dentyp;
			}
			set
			{
				if ((this._dentyp != value))
				{
					this._dentyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denval", DbType="Float")]
		public System.Nullable<double> denval
		{
			get
			{
				return this._denval;
			}
			set
			{
				if ((this._denval != value))
				{
					this._denval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kst1", DbType="Float")]
		public System.Nullable<double> kst1
		{
			get
			{
				return this._kst1;
			}
			set
			{
				if ((this._kst1 != value))
				{
					this._kst1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsb1", DbType="Float")]
		public System.Nullable<double> nsb1
		{
			get
			{
				return this._nsb1;
			}
			set
			{
				if ((this._nsb1 != value))
				{
					this._nsb1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esh1", DbType="Float")]
		public System.Nullable<double> esh1
		{
			get
			{
				return this._esh1;
			}
			set
			{
				if ((this._esh1 != value))
				{
					this._esh1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kst2", DbType="Float")]
		public System.Nullable<double> kst2
		{
			get
			{
				return this._kst2;
			}
			set
			{
				if ((this._kst2 != value))
				{
					this._kst2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsb2", DbType="Float")]
		public System.Nullable<double> nsb2
		{
			get
			{
				return this._nsb2;
			}
			set
			{
				if ((this._nsb2 != value))
				{
					this._nsb2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esh2", DbType="Float")]
		public System.Nullable<double> esh2
		{
			get
			{
				return this._esh2;
			}
			set
			{
				if ((this._esh2 != value))
				{
					this._esh2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kst3", DbType="Float")]
		public System.Nullable<double> kst3
		{
			get
			{
				return this._kst3;
			}
			set
			{
				if ((this._kst3 != value))
				{
					this._kst3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsb3", DbType="Float")]
		public System.Nullable<double> nsb3
		{
			get
			{
				return this._nsb3;
			}
			set
			{
				if ((this._nsb3 != value))
				{
					this._nsb3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esh3", DbType="Float")]
		public System.Nullable<double> esh3
		{
			get
			{
				return this._esh3;
			}
			set
			{
				if ((this._esh3 != value))
				{
					this._esh3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kst4", DbType="Float")]
		public System.Nullable<double> kst4
		{
			get
			{
				return this._kst4;
			}
			set
			{
				if ((this._kst4 != value))
				{
					this._kst4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsb4", DbType="Float")]
		public System.Nullable<double> nsb4
		{
			get
			{
				return this._nsb4;
			}
			set
			{
				if ((this._nsb4 != value))
				{
					this._nsb4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esh4", DbType="Float")]
		public System.Nullable<double> esh4
		{
			get
			{
				return this._esh4;
			}
			set
			{
				if ((this._esh4 != value))
				{
					this._esh4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om11", DbType="Float")]
		public System.Nullable<double> om11
		{
			get
			{
				return this._om11;
			}
			set
			{
				if ((this._om11 != value))
				{
					this._om11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om21", DbType="Float")]
		public System.Nullable<double> om21
		{
			get
			{
				return this._om21;
			}
			set
			{
				if ((this._om21 != value))
				{
					this._om21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om31", DbType="Float")]
		public System.Nullable<double> om31
		{
			get
			{
				return this._om31;
			}
			set
			{
				if ((this._om31 != value))
				{
					this._om31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om41", DbType="Float")]
		public System.Nullable<double> om41
		{
			get
			{
				return this._om41;
			}
			set
			{
				if ((this._om41 != value))
				{
					this._om41 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om51", DbType="Float")]
		public System.Nullable<double> om51
		{
			get
			{
				return this._om51;
			}
			set
			{
				if ((this._om51 != value))
				{
					this._om51 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om12", DbType="Float")]
		public System.Nullable<double> om12
		{
			get
			{
				return this._om12;
			}
			set
			{
				if ((this._om12 != value))
				{
					this._om12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om22", DbType="Float")]
		public System.Nullable<double> om22
		{
			get
			{
				return this._om22;
			}
			set
			{
				if ((this._om22 != value))
				{
					this._om22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om32", DbType="Float")]
		public System.Nullable<double> om32
		{
			get
			{
				return this._om32;
			}
			set
			{
				if ((this._om32 != value))
				{
					this._om32 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om42", DbType="Float")]
		public System.Nullable<double> om42
		{
			get
			{
				return this._om42;
			}
			set
			{
				if ((this._om42 != value))
				{
					this._om42 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om52", DbType="Float")]
		public System.Nullable<double> om52
		{
			get
			{
				return this._om52;
			}
			set
			{
				if ((this._om52 != value))
				{
					this._om52 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om13", DbType="Float")]
		public System.Nullable<double> om13
		{
			get
			{
				return this._om13;
			}
			set
			{
				if ((this._om13 != value))
				{
					this._om13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om23", DbType="Float")]
		public System.Nullable<double> om23
		{
			get
			{
				return this._om23;
			}
			set
			{
				if ((this._om23 != value))
				{
					this._om23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om33", DbType="Float")]
		public System.Nullable<double> om33
		{
			get
			{
				return this._om33;
			}
			set
			{
				if ((this._om33 != value))
				{
					this._om33 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om43", DbType="Float")]
		public System.Nullable<double> om43
		{
			get
			{
				return this._om43;
			}
			set
			{
				if ((this._om43 != value))
				{
					this._om43 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om53", DbType="Float")]
		public System.Nullable<double> om53
		{
			get
			{
				return this._om53;
			}
			set
			{
				if ((this._om53 != value))
				{
					this._om53 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om14", DbType="Float")]
		public System.Nullable<double> om14
		{
			get
			{
				return this._om14;
			}
			set
			{
				if ((this._om14 != value))
				{
					this._om14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om24", DbType="Float")]
		public System.Nullable<double> om24
		{
			get
			{
				return this._om24;
			}
			set
			{
				if ((this._om24 != value))
				{
					this._om24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om34", DbType="Float")]
		public System.Nullable<double> om34
		{
			get
			{
				return this._om34;
			}
			set
			{
				if ((this._om34 != value))
				{
					this._om34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om44", DbType="Float")]
		public System.Nullable<double> om44
		{
			get
			{
				return this._om44;
			}
			set
			{
				if ((this._om44 != value))
				{
					this._om44 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_om54", DbType="Float")]
		public System.Nullable<double> om54
		{
			get
			{
				return this._om54;
			}
			set
			{
				if ((this._om54 != value))
				{
					this._om54 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ded", DbType="Int")]
		public System.Nullable<int> ded
		{
			get
			{
				return this._ded;
			}
			set
			{
				if ((this._ded != value))
				{
					this._ded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sts", DbType="DateTime")]
		public System.Nullable<System.DateTime> sts
		{
			get
			{
				return this._sts;
			}
			set
			{
				if ((this._sts != value))
				{
					this._sts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="NChar(50)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam2", DbType="NChar(50)")]
		public string nam2
		{
			get
			{
				return this._nam2;
			}
			set
			{
				if ((this._nam2 != value))
				{
					this._nam2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adr", DbType="NChar(50)")]
		public string adr
		{
			get
			{
				return this._adr;
			}
			set
			{
				if ((this._adr != value))
				{
					this._adr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_life", DbType="NChar(225)")]
		public string life
		{
			get
			{
				return this._life;
			}
			set
			{
				if ((this._life != value))
				{
					this._life = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deth", DbType="NChar(225)")]
		public string deth
		{
			get
			{
				return this._deth;
			}
			set
			{
				if ((this._deth != value))
				{
					this._deth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phon", DbType="NChar(15)")]
		public string phon
		{
			get
			{
				return this._phon;
			}
			set
			{
				if ((this._phon != value))
				{
					this._phon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phon2", DbType="NChar(15)")]
		public string phon2
		{
			get
			{
				return this._phon2;
			}
			set
			{
				if ((this._phon2 != value))
				{
					this._phon2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amil", DbType="NChar(20)")]
		public string amil
		{
			get
			{
				return this._amil;
			}
			set
			{
				if ((this._amil != value))
				{
					this._amil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NChar(15)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this._fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rkm", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> rkm
		{
			get
			{
				return this._rkm;
			}
			set
			{
				if ((this._rkm != value))
				{
					this._rkm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tday", DbType="DateTime")]
		public System.Nullable<System.DateTime> tday
		{
			get
			{
				return this._tday;
			}
			set
			{
				if ((this._tday != value))
				{
					this._tday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam3", DbType="NChar(50)")]
		public string nam3
		{
			get
			{
				return this._nam3;
			}
			set
			{
				if ((this._nam3 != value))
				{
					this._nam3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos1", DbType="NChar(50)")]
		public string pos1
		{
			get
			{
				return this._pos1;
			}
			set
			{
				if ((this._pos1 != value))
				{
					this._pos1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos2", DbType="NChar(50)")]
		public string pos2
		{
			get
			{
				return this._pos2;
			}
			set
			{
				if ((this._pos2 != value))
				{
					this._pos2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos3", DbType="NChar(50)")]
		public string pos3
		{
			get
			{
				return this._pos3;
			}
			set
			{
				if ((this._pos3 != value))
				{
					this._pos3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adr1", DbType="NChar(50)")]
		public string adr1
		{
			get
			{
				return this._adr1;
			}
			set
			{
				if ((this._adr1 != value))
				{
					this._adr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adr2", DbType="NChar(50)")]
		public string adr2
		{
			get
			{
				return this._adr2;
			}
			set
			{
				if ((this._adr2 != value))
				{
					this._adr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adr3", DbType="NChar(50)")]
		public string adr3
		{
			get
			{
				return this._adr3;
			}
			set
			{
				if ((this._adr3 != value))
				{
					this._adr3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numall1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> numall1
		{
			get
			{
				return this._numall1;
			}
			set
			{
				if ((this._numall1 != value))
				{
					this._numall1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numall2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> numall2
		{
			get
			{
				return this._numall2;
			}
			set
			{
				if ((this._numall2 != value))
				{
					this._numall2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numall3", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> numall3
		{
			get
			{
				return this._numall3;
			}
			set
			{
				if ((this._numall3 != value))
				{
					this._numall3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cur", DbType="Int")]
		public System.Nullable<int> cur
		{
			get
			{
				return this._cur;
			}
			set
			{
				if ((this._cur != value))
				{
					this._cur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_he1", DbType="Int")]
		public System.Nullable<int> he1
		{
			get
			{
				return this._he1;
			}
			set
			{
				if ((this._he1 != value))
				{
					this._he1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_he2", DbType="Int")]
		public System.Nullable<int> he2
		{
			get
			{
				return this._he2;
			}
			set
			{
				if ((this._he2 != value))
				{
					this._he2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc", DbType="Int")]
		public System.Nullable<int> doc
		{
			get
			{
				return this._doc;
			}
			set
			{
				if ((this._doc != value))
				{
					this._doc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rpos1", DbType="Float")]
		public System.Nullable<double> rpos1
		{
			get
			{
				return this._rpos1;
			}
			set
			{
				if ((this._rpos1 != value))
				{
					this._rpos1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rpos2", DbType="Float")]
		public System.Nullable<double> rpos2
		{
			get
			{
				return this._rpos2;
			}
			set
			{
				if ((this._rpos2 != value))
				{
					this._rpos2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rhel1", DbType="Float")]
		public System.Nullable<double> rhel1
		{
			get
			{
				return this._rhel1;
			}
			set
			{
				if ((this._rhel1 != value))
				{
					this._rhel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rhel2", DbType="Float")]
		public System.Nullable<double> rhel2
		{
			get
			{
				return this._rhel2;
			}
			set
			{
				if ((this._rhel2 != value))
				{
					this._rhel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_racc1", DbType="Float")]
		public System.Nullable<double> racc1
		{
			get
			{
				return this._racc1;
			}
			set
			{
				if ((this._racc1 != value))
				{
					this._racc1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_racc2", DbType="Float")]
		public System.Nullable<double> racc2
		{
			get
			{
				return this._racc2;
			}
			set
			{
				if ((this._racc2 != value))
				{
					this._racc2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rdep1", DbType="Float")]
		public System.Nullable<double> rdep1
		{
			get
			{
				return this._rdep1;
			}
			set
			{
				if ((this._rdep1 != value))
				{
					this._rdep1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rdep2", DbType="Float")]
		public System.Nullable<double> rdep2
		{
			get
			{
				return this._rdep2;
			}
			set
			{
				if ((this._rdep2 != value))
				{
					this._rdep2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rpen1", DbType="Float")]
		public System.Nullable<double> rpen1
		{
			get
			{
				return this._rpen1;
			}
			set
			{
				if ((this._rpen1 != value))
				{
					this._rpen1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rpen2", DbType="Float")]
		public System.Nullable<double> rpen2
		{
			get
			{
				return this._rpen2;
			}
			set
			{
				if ((this._rpen2 != value))
				{
					this._rpen2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pascod", DbType="Int")]
		public System.Nullable<int> pascod
		{
			get
			{
				return this._pascod;
			}
			set
			{
				if ((this._pascod != value))
				{
					this._pascod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_omok", DbType="Int")]
		public System.Nullable<int> omok
		{
			get
			{
				return this._omok;
			}
			set
			{
				if ((this._omok != value))
				{
					this._omok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modasdad", DbType="Int")]
		public System.Nullable<int> modasdad
		{
			get
			{
				return this._modasdad;
			}
			set
			{
				if ((this._modasdad != value))
				{
					this._modasdad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pen1", DbType="Float")]
		public System.Nullable<double> pen1
		{
			get
			{
				return this._pen1;
			}
			set
			{
				if ((this._pen1 != value))
				{
					this._pen1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pen2", DbType="Float")]
		public System.Nullable<double> pen2
		{
			get
			{
				return this._pen2;
			}
			set
			{
				if ((this._pen2 != value))
				{
					this._pen2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pen3", DbType="Float")]
		public System.Nullable<double> pen3
		{
			get
			{
				return this._pen3;
			}
			set
			{
				if ((this._pen3 != value))
				{
					this._pen3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pen4", DbType="Float")]
		public System.Nullable<double> pen4
		{
			get
			{
				return this._pen4;
			}
			set
			{
				if ((this._pen4 != value))
				{
					this._pen4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penall", DbType="Float")]
		public System.Nullable<double> penall
		{
			get
			{
				return this._penall;
			}
			set
			{
				if ((this._penall != value))
				{
					this._penall = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_bouns")]
	public partial class T_boun
	{
		
		private int _cod;
		
		private int _ser;
		
		private System.Nullable<int> _modd;
		
		private System.Nullable<double> _kstyer;
		
		private System.Nullable<double> _rat1;
		
		private System.Nullable<double> _rat2;
		
		private System.Nullable<double> _rat3;
		
		private System.Nullable<double> _calc;
		
		private System.Nullable<double> _calcrat;
		
		public T_boun()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser", DbType="Int NOT NULL")]
		public int ser
		{
			get
			{
				return this._ser;
			}
			set
			{
				if ((this._ser != value))
				{
					this._ser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modd", DbType="Int")]
		public System.Nullable<int> modd
		{
			get
			{
				return this._modd;
			}
			set
			{
				if ((this._modd != value))
				{
					this._modd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kstyer", DbType="Float")]
		public System.Nullable<double> kstyer
		{
			get
			{
				return this._kstyer;
			}
			set
			{
				if ((this._kstyer != value))
				{
					this._kstyer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rat1", DbType="Float")]
		public System.Nullable<double> rat1
		{
			get
			{
				return this._rat1;
			}
			set
			{
				if ((this._rat1 != value))
				{
					this._rat1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rat2", DbType="Float")]
		public System.Nullable<double> rat2
		{
			get
			{
				return this._rat2;
			}
			set
			{
				if ((this._rat2 != value))
				{
					this._rat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rat3", DbType="Float")]
		public System.Nullable<double> rat3
		{
			get
			{
				return this._rat3;
			}
			set
			{
				if ((this._rat3 != value))
				{
					this._rat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calc", DbType="Float")]
		public System.Nullable<double> calc
		{
			get
			{
				return this._calc;
			}
			set
			{
				if ((this._calc != value))
				{
					this._calc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calcrat", DbType="Float")]
		public System.Nullable<double> calcrat
		{
			get
			{
				return this._calcrat;
			}
			set
			{
				if ((this._calcrat != value))
				{
					this._calcrat = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_dentyp")]
	public partial class T_dentyp
	{
		
		private int _cod;
		
		private string _nam;
		
		public T_dentyp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="NChar(30)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_doc")]
	public partial class T_doc
	{
		
		private int _cod;
		
		private int _doc;
		
		public T_doc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doc", DbType="Int NOT NULL")]
		public int doc
		{
			get
			{
				return this._doc;
			}
			set
			{
				if ((this._doc != value))
				{
					this._doc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_docjop")]
	public partial class T_docjop
	{
		
		private int _cod;
		
		private int _ser;
		
		private string _nam;
		
		public T_docjop()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser", DbType="Int NOT NULL")]
		public int ser
		{
			get
			{
				return this._ser;
			}
			set
			{
				if ((this._ser != value))
				{
					this._ser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="NChar(40)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_docnam")]
	public partial class T_docnam
	{
		
		private int _cod;
		
		private int _idn;
		
		private string _nam;
		
		public T_docnam()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idn", DbType="Int NOT NULL")]
		public int idn
		{
			get
			{
				return this._idn;
			}
			set
			{
				if ((this._idn != value))
				{
					this._idn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="NChar(40)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_instypnams")]
	public partial class T_instypnam
	{
		
		private int _cod;
		
		private string _nam;
		
		public T_instypnam()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Char(80)")]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this._nam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_kst9")]
	public partial class T_kst9
	{
		
		private int _cod;
		
		private int _moda;
		
		private System.Nullable<double> _kst;
		
		private System.Nullable<double> _edk;
		
		private System.Nullable<double> _omm;
		
		private System.Nullable<double> _oms;
		
		public T_kst9()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this._cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moda", DbType="Int NOT NULL")]
		public int moda
		{
			get
			{
				return this._moda;
			}
			set
			{
				if ((this._moda != value))
				{
					this._moda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kst", DbType="Float")]
		public System.Nullable<double> kst
		{
			get
			{
				return this._kst;
			}
			set
			{
				if ((this._kst != value))
				{
					this._kst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edk", DbType="Float")]
		public System.Nullable<double> edk
		{
			get
			{
				return this._edk;
			}
			set
			{
				if ((this._edk != value))
				{
					this._edk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_omm", DbType="Float")]
		public System.Nullable<double> omm
		{
			get
			{
				return this._omm;
			}
			set
			{
				if ((this._omm != value))
				{
					this._omm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oms", DbType="Float")]
		public System.Nullable<double> oms
		{
			get
			{
				return this._oms;
			}
			set
			{
				if ((this._oms != value))
				{
					this._oms = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_passcod")]
	public partial class T_passcod
	{
		
		private int _passcod;
		
		private string _usernam;
		
		private string _pasword;
		
		public T_passcod()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passcod", DbType="Int NOT NULL")]
		public int passcod
		{
			get
			{
				return this._passcod;
			}
			set
			{
				if ((this._passcod != value))
				{
					this._passcod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usernam", DbType="Char(30)")]
		public string usernam
		{
			get
			{
				return this._usernam;
			}
			set
			{
				if ((this._usernam != value))
				{
					this._usernam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasword", DbType="NChar(14) NOT NULL", CanBeNull=false)]
		public string pasword
		{
			get
			{
				return this._pasword;
			}
			set
			{
				if ((this._pasword != value))
				{
					this._pasword = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User
	{
		
		private string _UserName;
		
		private System.Nullable<int> _Password;
		
		private System.Nullable<int> _SessionID;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Int")]
		public System.Nullable<int> Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="Int")]
		public System.Nullable<int> SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this._SessionID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
